# Site settings
title: "Yuetong Fang"
email: "yuetong.fang@univ-angers.fr"
description: "Personal Academic Website"
baseurl: ""
url: "https://yuetong-fang.github.io"
github_username: yuetong-fang

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Navigation
show_downloads: false

# Custom variables
author: "Yuetong Fang"