title: Yuetong FANG's Homepage
description: Personal academic website of Yuetong Fang
baseurl: ""
url: "https://username.github.io"
theme: minima

# Navigation
nav_external_links:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Teaching
    url: /teaching
  - title: Others
    url: /others

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
primary_color: "#6a1b9a"
primary_light: "#9c4dcc"
primary_dark: "#38006b"
footer_color: "#e1bee7"